name: CI

on:
  push:
    branches:
      - main
      - main_*
      - fluent2-tokens
      - fluent2-colors
  pull_request:
    branches:
      - main
      - main_*
      - fluent2-tokens
      - fluent2-colors

jobs:
  validation:
    runs-on: macos-12
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v3
    - name: Switch to current version of Xcode
      run: scripts/xcode_select_current_version.sh
    - name: pod lib lint
      run: scripts/podliblint.sh
    - name: validation
      run: scripts/validation.sh
  xcodebuild:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        build_command: [
          'macos_build FluentUITestApp-macOS Debug build test -destination "platform=macOS,arch=x86_64"',
        ]

    steps:
    - uses: actions/checkout@v3
    - name: Switch to current version of Xcode
      run: scripts/xcode_select_current_version.sh
    - name: scripts/xcodebuild_wrapper.sh ${{ matrix.build_command }}
      run: scripts/xcodebuild_wrapper.sh ${{ matrix.build_command }}
